openapi: 3.0.0
info:
  title: Air Ticket Booking API
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid email or password

  /api/register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name: { type: string }
                last_name: { type: string }
                email: { type: string }
                password: { type: string }
                passport_number: { type: string }
      responses:
        '200':
          description: User registered

  /flights:
    get:
      summary: Get all flights
      responses:
        '200':
          description: A list of flights

  /search:
    post:
      summary: Search flights
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from: { type: string }
                to: { type: string }
                departure_date: { type: string, format: date }
      responses:
        '200':
          description: Matching flights

  /seats:
    get:
      summary: Get seat availability
      responses:
        '200':
          description: Seat info

  /booking:
    post:
      summary: Book a flight (requires auth)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                flight_id: { type: integer }
                seat:
                  type: array
                  items: { type: string }
      responses:
        '201':
          description: Booking successful

  /payments:
    post:
      summary: Create a payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                booking_id: { type: integer }
                amount: { type: number }
                payment_method: { type: string }
      responses:
        '200':
          description: Payment created

  /payments-confirmed:
    post:
      summary: Confirm payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                booking_id: { type: integer }
      responses:
        '200':
          description: Payment confirmed
